import {
  ShoppingCart,
  Coffee,
  BookOpen,
  Dumbbell,
  PartyPopper,
  Car,
  Wallet,
  PlusCircle,
  TrendingUp,
  Tag,
  Home,
  Utensils,
  Plane,
  Gift,
  Heart,
  Phone,
  Film,
  Gamepad2,
  Briefcase,
  GraduationCap,
  PawPrint,
  Baby,
  Shirt,
  Wrench,
  Landmark,
  PiggyBank,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  coffee: Coffee,
  "book-open": BookOpen,
  dumbbell: Dumbbell,
  "party-popper": PartyPopper,
  car: Car,
  wallet: Wallet,
  "plus-circle": PlusCircle,
  "trending-up": TrendingUp,
  tag: Tag,
  home: Home,
  utensils: Utensils,
  plane: Plane,
  gift: Gift,
  heart: Heart,
  phone: Phone,
  film: Film,
  gamepad: Gamepad2,
  briefcase: Briefcase,
  "graduation-cap": GraduationCap,
  "paw-print": PawPrint,
  baby: Baby,
  shirt: Shirt,
  wrench: Wrench,
  landmark: Landmark,
  "piggy-bank": PiggyBank,
};

export const ICON_KEYS = Object.keys(ICONS);

export function getIcon(key: string): LucideIcon {
  return ICONS[key] ?? Tag;
}
